=== sunxing109/DeepVideoAnalytics/client/dvaclient/schema.json
{
  "id": "http://www.visualdata.network/schema",
  "$schema": "http://json-schema.org/draft-06/schema#",
  "description": "A DVAPQL script",
  "definitions": {
    "task_arguments": {
      "description": "task_arguments",
      "type": "object",
      "properties": {
        "map": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/task"
          }
        },
        "reduce": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/reduce_task"
          }
        }
      }
    },
    "reduce_task_arguments": {
      "description": "task_arguments",
      "type": "object",
      "properties": {
        "map": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/task"
          }
        },
        "reduce_target": {
          "type": "string"
        }
      },
      "required": [
        "reduce_target"
      ]
    },
    "task": {
      "description": "A task",
      "type": "object",
      "properties": {
        "operation": {
          "type": "string"
        },
        "arguments": {
          "$ref": "#/definitions/task_arguments"
        }
      },
      "required": [
        "operation",
        "arguments"
      ]
    },
    "reduce_task": {
      "description": "A reduce task",
      "type": "object",
      "properties": {
        "arguments": {
          "$ref": "#/definitions/reduce_task_arguments"
        }
      },
      "required": [
        "arguments"
      ]
    },
    "create": {
      "description": "A spec for creating an object and task",
      "type": "object",
      "properties": {
        "spec": {},
        "MODEL": {
          "type": "string"
        }
      },
      "required": [
        "spec",
        "MODEL"
      ]
    },
    "delete": {}
  },
  "properties": {
    "description": {
      "type": "string"
    },
    "image_data_b64": {
      "type": "string"
    },
    "process_type": {
      "type": "string"
    },
    "create": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/create"
      }
    },
    "map": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/task"
      }
    },
    "reduce": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/reduce_task"
      }
    },
    "delete": {
      "type": "array"
    }
  },
  "required": [
    "process_type"
  ]
}

=== sunxing109/DeepVideoAnalytics/configs/custom_defaults/init_process.json
{
  "reduce": [],
  "map": [
    {
      "operation": "perform_import",
      "video_id": "__created__0",
      "arguments": {
        "map": [
          {
            "operation": "perform_video_segmentation",
            "arguments": {
              "map": [
                {
                  "operation": "perform_video_decode",
                  "arguments": {
                    "map": [
                      {
                        "operation": "perform_detection",
                        "arguments": {
                          "map": [
                            {
                              "operation": "perform_indexing",
                              "arguments": {
                                "trainedmodel_selector":{"name":"inception"},
                                "target": "regions",
                                "filters": {
                                  "event_id": "__parent_event__",
                                  "w__gte": 50,
                                  "h__gte": 50
                                }
                              }
                            }
                          ],
                          "trainedmodel_selector":{"name":"coco"},
                          "filters": "__parent__"
                        }
                      },
                      {
                        "operation": "perform_detection",
                        "arguments": {
                          "map": [
                            {
                              "operation": "perform_indexing",
                              "arguments": {
                                "trainedmodel_selector":{"name":"facenet"},
                                "target": "regions",
                                "filters": {
                                  "event_id": "__parent_event__"
                                },
                                "map": [
                                  {
                                    "operation": "perform_index_approximation",
                                    "arguments": {
                                      "target": "index_entries",
                                      "trainedmodel_selector":{"shasum":"93be2f99d432a7ce2d1626107659510755ea3815"},
                                      "filters": {
                                        "event_id": "__parent_event__"
                                      }
                                    }
                                  }
                                ]
                              }
                            }
                          ],
                          "trainedmodel_selector":{"name":"face"},
                          "filters": "__parent__"
                        }
                      },
                      {
                        "operation": "perform_indexing",
                        "arguments": {
                          "trainedmodel_selector":{"name":"inception"},
                          "target": "frames",
                          "filters": "__parent__",
                          "map": [
                            {
                              "operation": "perform_index_approximation",
                              "arguments": {
                                "target": "index_entries",
                                "trainedmodel_selector":{"shasum":"86689432ac09d86dd95d7d3ed57227d27eb09c81"},
                                "filters": {
                                  "event_id": "__parent_event__"
                                }
                              }
                            }
                          ]
                        }
                      },
                      {
                        "operation": "perform_analysis",
                        "arguments": {
                          "trainedmodel_selector":{"name":"tagger"},
                          "target": "frames",
                          "filters": "__parent__"
                        }
                      }
                    ],
                    "rate": 30,
                    "segments_batch_size": 10
                  }
                }
              ]
            }
          }
        ]
      }
    },
    {
      "operation": "perform_import",
      "video_id": "__created__1",
      "arguments": {
        "map": [
          {
            "operation": "perform_dataset_extraction",
            "arguments": {
              "map": [
                {
                  "operation": "perform_detection",
                  "arguments": {
                    "frames_batch_size": 500,
                    "map": [
                      {
                        "operation": "perform_indexing",
                        "arguments": {
                          "trainedmodel_selector":{"name":"inception"},
                          "target": "regions",
                          "filters": {
                            "event_id": "__parent_event__",
                            "w__gte": 50,
                            "h__gte": 50
                          },
                          "map": [
                            {
                              "operation": "perform_index_approximation",
                              "arguments": {
                                "target": "index_entries",
                                "trainedmodel_selector":{"shasum":"86689432ac09d86dd95d7d3ed57227d27eb09c81"},
                                "filters": {
                                  "event_id": "__parent_event__"
                                }
                              }
                            }
                          ]
                        }
                      }
                    ],
                    "trainedmodel_selector":{"name":"coco"}
                  }
                },
                {
                  "operation": "perform_detection",
                  "arguments": {
                    "frames_batch_size": 500,
                    "map": [
                      {
                        "operation": "perform_indexing",
                        "arguments": {
                          "trainedmodel_selector":{"name":"facenet"},
                          "target": "regions",
                          "filters": {
                            "event_id": "__parent_event__"
                          },
                          "map": [
                            {
                              "operation": "perform_index_approximation",
                              "arguments": {
                                "target": "index_entries",
                                "trainedmodel_selector":{"shasum":"93be2f99d432a7ce2d1626107659510755ea3815"},
                                "filters": {
                                  "event_id": "__parent_event__"
                                }
                              }
                            }
                          ]
                        }
                      }
                    ],
                    "trainedmodel_selector":{"name":"face"}
                  }
                },
                {
                  "operation": "perform_indexing",
                  "arguments": {
                    "frames_batch_size": 500,
                    "trainedmodel_selector":{"name":"inception"},
                    "target": "frames",
                    "map": [
                      {
                        "operation": "perform_index_approximation",
                        "arguments": {
                          "target": "index_entries",
                          "trainedmodel_selector":{"shasum":"86689432ac09d86dd95d7d3ed57227d27eb09c81"},
                          "filters": {
                            "event_id": "__parent_event__"
                          }
                        }
                      }
                    ]
                  }
                },
                {
                  "operation": "perform_analysis",
                  "arguments": {
                    "frames_batch_size": 500,
                    "target": "frames",
                    "trainedmodel_selector":{"name":"tagger"}
                  }
                }
              ]
            }
          }
        ]
      }
    },
    {
      "operation": "perform_import",
      "video_id": "__created__2",
      "arguments": {
        "map": [
          {
            "operation": "perform_dataset_extraction",
            "arguments": {
              "map": [
                {
                  "operation": "perform_detection",
                  "arguments": {
                    "frames_batch_size": 500,
                    "filters": "__parent__",
                    "trainedmodel_selector":{"name":"textbox"},
                    "target": "frames",
                    "map": [
                      {
                        "operation": "perform_analysis",
                        "arguments": {
                          "trainedmodel_selector":{"name":"crnn"},
                          "target": "regions",
                          "filters": {
                            "event_id": "__parent_event__"
                          }
                        }
                      }
                    ]
                  }
                },
                {
                  "operation": "perform_detection",
                  "arguments": {
                    "frames_batch_size": 500,
                    "map": [
                      {
                        "operation": "perform_indexing",
                        "arguments": {
                          "trainedmodel_selector":{"name":"inception"},
                          "target": "regions",
                          "filters": {
                            "event_id": "__parent_event__",
                            "w__gte": 50,
                            "h__gte": 50
